version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pontoon_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MYSQLpassword_2setting   # 设置 MySQL root 密码
      MYSQL_DATABASE: pontoon_db   # 创建数据库
      MYSQL_USER: pontoon   # 创建用户
      MYSQL_PASSWORD: databasePass_2setting   # 设置用户密码
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pMYSQLpassword_2setting"]   # 根据root实际密码修改
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pontoon-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pontoon_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"   # phpMyAdmin 在宿主的 8081
    depends_on:
      - db
    networks:
      - pontoon-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pontoon_backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pontoon-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pontoon_frontend
    restart: unless-stopped
    ports:
      - "8080:80"   # 前端通过 nginx 暴露到宿主 80（如宿主已占用，可改 8080:80）
    networks:
      - pontoon-net

volumes:
  db_data:

networks:
  pontoon-net:
    driver: bridge